export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const DASHBOARD_DATA = "DASHBOARD_DATA";

//PROFILE REDUCER
export const AUTH_USER_LOAD = "AUTH_USER_LOAD";
export const AUTH_USER_LOAD_ERROR = "AUTH_USER_LOAD_ERROR";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

// PAYMENT REDUCER
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const GET_PAYMENT_DETAILS = "GET_PAYMENT_DETAILS";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const GET_PAYMENT = "GET_PAYMENT";

// GRADE REDUCER
export const GET_GRADE = "GET_GRADE";
export const SYNC_GRADES = "SYNC_GRADES";

// STUDENT REDUCER
export const SYNC_ALL_STUDENTS = "SYNC_ALL_STUDENTS";
export const SYNC_RECENT_STUDENTS = "SYNC_RECENT_STUDENTS";
export const GET_SYNC_STATUS = "GET_SYNC_STATUS";
export const GET_STUDENT = "GET_STUDENT";

// TENANT REDUCER
export const SET_TENANT = "SET_TENANT";

// EXPENSE REDUCER
export const CREATE_EXPENSE = "CREATE_EXPENSE";
export const GET_EXPENSES = "GET_EXPENSES";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";

// REVENUE REDUCER
export const CREATE_REVENUE = "CREATE_REVENUE";
export const GET_REVENUES = "GET_REVENUES";
export const UPDATE_REVENUE = "UPDATE_REVENUE";
export const DELETE_REVENUE = "DELETE_REVENUE";

// EXPENSE CATEGORY REDUCER
export const CREATE_EXPENSE_CATEGORY = "CREATE_EXPENSE_CATEGORY";
export const GET_EXPENSE_CATEGORIES = "GET_EXPENSE_CATEGORIES";
export const UPDATE_EXPENSE_CATEGORY = "UPDATE_EXPENSE_CATEGORY";
export const DELETE_EXPENSE_CATEGORY = "DELETE_EXPENSE_CATEGORY";

// REVENUE CATEGORY REDUCER
export const CREATE_REVENUE_CATEGORY = "CREATE_REVENUE_CATEGORY";
export const GET_REVENUE_CATEGORIES = "GET_REVENUE_CATEGORIES";
export const UPDATE_REVENUE_CATEGORY = "UPDATE_REVENUE_CATEGORY";
export const DELETE_REVENUE_CATEGORY = "DELETE_REVENUE_CATEGORY";

// REPORT REDUCER
export const GET_MONTHLY_STATS = "GET_MONTHLY_STATS";
export const GET_FILTERED_STATS = "GET_FILTERED_STATS";
export const GET_GRADE_BREAKDOWN = "GET_GRADE_BREAKDOWN";
export const GET_SHIFT_BREAKDOWN = "GET_SHIFT_BREAKDOWN";
export const GET_BATCH_BREAKDOWN = "GET_BATCH_BREAKDOWN";
export const GET_MONTHLY_INCOME_EXPENSE = "GET_MONTHLY_INCOME_EXPENSE";
export const GET_YEARLY_EXPENSE_REPORT = "GET_YEARLY_EXPENSE_REPORT";
export const GET_YEARLY_INCOME_REPORT = "GET_YEARLY_INCOME_REPORT";
export const GET_SCHOOL_PRIMARY_REPORT = "GET_SCHOOL_PRIMARY_REPORT";


